### ISSUE TITLE
Uninstalling all languages returns an error, but it succeeded. 

### ISSUE THREAD

**Issue by simjanos-dev** [simjanos-dev/LinguaCafe#320]

**Comment by simjanos-dev** [comment]
Something is weird on the python side I think. Multiple times it does not log the request

```
Listening on http://0.0.0.0:8678/
Hit Ctrl-C to quit.

172.19.0.5 - - [20/Aug/2024 08:30:06] "GET /models/list HTTP/1.1" 200 2
172.19.0.5 - - [20/Aug/2024 08:30:20] "DELETE /models/remove HTTP/1.1" 202 28
172.19.0.5 - - [20/Aug/2024 08:30:21] "GET /models/list HTTP/1.1" 200 2
172.19.0.5 - - [20/Aug/2024 08:30:47] "POST /models/install HTTP/1.1" 200 45
172.19.0.5 - - [20/Aug/2024 08:30:48] "GET /models/list HTTP/1.1" 200 13
172.19.0.5 - - [20/Aug/2024 08:30:59] "DELETE /models/remove HTTP/1.1" 200 35
172.19.0.5 - - [20/Aug/2024 08:31:00] "GET /models/list HTTP/1.1" 200 2
  d

 
 172.19.0.5 - - [20/Aug/2024 08:32:06] "GET /models/list HTTP/1.1" 200 12
172.19.0.5 - - [20/Aug/2024 08:32:07] "GET /models/list HTTP/1.1" 200 12
172.19.0.5 - - [20/Aug/2024 08:32:10] "GET /models/list HTTP/1.1" 200 12
```

Before the last 3 lines I installed Japanese, but it produced no output in the logs. It returned an error on the front-end, but it was successful. The d character and new lines are from my keyboard, I though maybe my terminal was not updating for some reason.

**Comment by cblanken** [comment]
I ran across something similar. The error message and logs I saw are below. After clicking "Uninstall" it seems to have succeeded.

# Error message
![image](https://github.com/user-attachments/assets/07f2576e-5060-429c-91aa-0a32e833d7de)

## Error log from python service
```apache
172.18.0.5 - - [07/Oct/2024 18:19:01] "GET /models/list HTTP/1.1" 200 19
```
```python
Traceback (most recent call last):
  File "/usr/lib/python3.10/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/home/laravel/.local/lib/python3.10/site-packages/bottle.py", line 993, in __call__
    return self.wsgi(environ, start_response)
  File "/home/laravel/.local/lib/python3.10/site-packages/bottle.py", line 968, in wsgi
    out = self._cast(self._handle(environ))
  File "/home/laravel/.local/lib/python3.10/site-packages/bottle.py", line 876, in _handle
    return route.call(**args)
  File "/home/laravel/.local/lib/python3.10/site-packages/bottle.py", line 1759, in wrapper
    rv = callback(*a, **ka)
  File "/app/tokenizer.py", line 658, in model_remove
    shutil.rmtree("/var/www/html/storage/app/model")
  File "/usr/lib/python3.10/shutil.py", line 725, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.10/shutil.py", line 658, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.10/shutil.py", line 658, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.10/shutil.py", line 658, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  [Previous line repeated 1 more time]
  File "/usr/lib/python3.10/shutil.py", line 679, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
KeyboardInterrupt
```
```apache
172.18.0.5 - - [07/Oct/2024 18:19:21] "DELETE /models/remove HTTP/1.1" 500 59
```
